---
# See https://github.com/actions/virtual-environments
# https://github.com/marketplace/actions/setup-perl-environment

name: Test Code
permissions:
  contents: read
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '32 4 29 * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        perl: ['5.38', '5.36', '5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iq ExtUtils::MakeMaker Test::Most Test::Needs
          cpanm -q -n Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Pod::Coverage
          cpanm -iq --installdeps --notest .
      - name: Make Module
        run: |
          # find . -name build.log | xargs cat
          perl Makefile.PL
          make
      - name: Run Tests
        run: prove -l -b t
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
